Homepage products
ReCoded-Org/istanbul-capstone-ecommerce pull request #11
Opened 2020-07-21 19:26 UTC by OmarAlithawi

2020-07-22 12:43 UTC, MiraAr approved these changes

2020-07-22 13:29 UTC, emrerdem1 requested changes
Can you please run Prettier to get rid of unnecessary line-breaks in .scss file, every selector has to have only one line-break after closing curly braces according to what Louis said to me before. And there is spaces before commas such as `(12 ,1fr)`, it should be `(12, 1fr)`. If you can fix this too, that'd be great.

Other parts look great. :)

2020-07-25 13:07 UTC, OmarAlithawi commented
PTAL

2020-07-25 17:08 UTC, louisrli requested changes
not sure why the indentations are so big but please submit circleci in separate PR and fix the indentation and i'll look at this code

2020-07-25 17:08 UTC, louisrli commented on .circleci/config.yml
> +    steps:
this should not be in this pr

2020-07-25 17:08 UTC, louisrli commented on package.json
> +    "lint": "eslint '**/*.{js,jsx}'",
normally if you're using eslint and prettier you will be combining the integrations (google prettier eslint)

for short term, delete lint, try adding it in another PR

2020-07-25 17:08 UTC, louisrli commented on package.json
> +    "pretty": "prettier --write \"./**/*.{js,jsx}\""
this should include css files

2020-07-25 17:08 UTC, louisrli commented on src/components/home/Home.jsx
> +			<Products />
indentation is wrong

2020-07-25 17:08 UTC, louisrli commented on src/components/layout/productCard/ProductCard.jsx
> +		className: 'silderImages',
indentation still wrong please fix and i'll review this PR, write PTAL when ready

2020-07-25 17:08 UTC, louisrli commented on src/components/layout/productCard/style.scss
> +
way too many newlines

2020-07-25 17:09 UTC, louisrli commented
not sure why there's a branch called homepage. all PRs should be into dev branch. talk to abdulrahman please if you need help fixing this and please set up circleci asap

2020-07-27 19:07 UTC, louisrli commented
also you have two PRs with the exact same name

2020-07-28 18:17 UTC, closed without merging