Homepage products
ReCoded-Org/istanbul-capstone-ecommerce pull request #25
Opened 2020-07-28 18:16 UTC by OmarAlithawi

PTAL

2020-07-28 20:58 UTC, louisrli commented on src/components/layout/productCard/ProductCard.jsx
> +    className: "silderImages",
typo

2020-07-28 20:58 UTC, louisrli commented on src/components/layout/productCard/ProductCard.jsx
> +  const [isLiked, setIsLiked] = React.useState(false);
is this supposed to be loaded from firebase or something eventually? or props?

2020-07-28 20:58 UTC, louisrli commented on src/components/layout/productCard/ProductCard.jsx
> +        {/*doc-id = {props.productId[index]}*/}
commented code

2020-07-28 20:58 UTC, louisrli commented on src/components/layout/productCard/ProductCard.jsx
> +        {likeBtnHandler()}
these are not handlers, usually handlers is something like `onClick={handleClick}`

for these, just call them

`const slider`
`const likeBtn` 

and they should not be functions

2020-07-28 20:58 UTC, louisrli commented on src/components/products/Products.jsx
> +  const data = [
is this temporary until real products are placed? if so, add a comment indicating this

2020-07-28 20:58 UTC, louisrli commented on src/components/products/Products.jsx
> +      <Row>{renderProductsCards()}</Row>
just inline this map code, it's short enough that having the function is probably a bit more confusing

2020-07-29 07:00 UTC, OmarAlithawi commented
PTAL

2020-07-29 07:24 UTC, MiraAr approved these changes

2020-07-29 10:54 UTC, louisrli requested changes

2020-07-29 10:54 UTC, louisrli commented on src/components/layout/productCard/ProductCard.jsx
> +  // we will load isLiked from firebase and then set it to this state
capitalize we

2020-07-29 10:54 UTC, louisrli commented on src/components/layout/productCard/ProductCard.jsx
> +      <Col xs={8} md={5} lg={3} className="productCard"> {/*when we get the real product we need to add an id to each product*/}
don't do comments at end of line like this, it's ugly, put it after line 25

2020-07-29 10:54 UTC, louisrli commented on src/components/layout/productCard/ProductCard.jsx
> +        {isLiked ? (
so for these you should actually include them outside as variables, it makes the code cleaner. but i was saying that they should not be functions, they are simply variables.

```const slider = {
  return()
}
```
(in your old code you had `slider = () =>`

2020-07-29 11:13 UTC, OmarAlithawi commented
PTAL

2020-07-29 20:24 UTC, louisrli approved these changes

2020-07-29 20:24 UTC, louisrli commented on src/components/products/Products.jsx
> +
line 7 delete newline

2020-07-29 20:24 UTC, louisrli commented
fix merge conflicts and i believe you can merge yourself with approving reviews

2020-07-30 14:56 UTC, merged