adding language dropdown to navbar
ReCoded-Org/istanbul-capstone-ecommerce pull request #52
Opened 2020-08-08 08:24 UTC by MiraAr

2020-08-08 09:22 UTC, emrerdem1 commented
LGTM! 💯

2020-08-08 09:22 UTC, emrerdem1 approved these changes

2020-08-08 09:25 UTC, emrerdem1 commented on src/components/layout/nav/Navbar.jsx
> +            onClick={() => handleStatusOfIcons("IS_LANGUAGE_DROPDOWN_OPENED")}
Only this need to be changed into `className`.

2020-08-08 11:14 UTC, louisrli requested changes

2020-08-08 11:14 UTC, louisrli commented on src/components/header/Header.jsx
> +          <h1 className="headerTitle">{t("We Care About Your Health")}</h1>
this doesnt seem right, the translations are usually short keys, not full sentences?

2020-08-08 11:14 UTC, louisrli commented on src/components/locales/ar/translation.json
> +  "We Care About Your Health": "صحتكم تهمنا"
the key should be a short name like "title" or something, not the english version of the sentence

2020-08-09 18:28 UTC, MiraAr commented
PTAL

2020-08-09 18:35 UTC, louisrli approved these changes

2020-08-09 19:08 UTC, merged